In [1]:
import numpy as np

In [2]:
def relu(x, deriv=False):
    if deriv: return 1 * (x > 0)
    return np.maximum(x, 0)

streetlight = np.array([[1, 0, 1],
                        [0, 1, 1],
                        [0, 0, 1],
                        [1, 1, 1]])
results = np.array([1, 1, 0, 0])

learning_rate = 0.1
hidden_nodes = 4

weights_l1 = np.random.randn(3, hidden_nodes)
weights_l2 = np.random.randn(hidden_nodes, 1)

In [3]:
for j in range(100):
    total_layer_2_error = 0
    for i in range(len(streetlight)):
        layer_0 = streetlight[i:i+1]
        layer_1 = relu(np.dot(layer_0, weights_l1))
        layer_2 = np.dot(layer_1, weights_l2)
        layer_2_error = (layer_2 - results[i:i+1]) ** 2
        total_layer_2_error += layer_2_error
        layer_2_delta = 2 * (layer_2 - results[i:i+1])
        layer_1_delta = layer_2_delta.dot(weights_l2.T) * relu(layer_1, deriv=True)

        weights_l1 -= learning_rate * layer_0.T.dot(layer_1_delta)
        weights_l2 -= learning_rate * layer_1.T.dot(layer_2_delta)
    if j % 20 == 0:
        print("Error: {}".format(total_layer_2_error))
        print(weights_l1)
        print(weights_l2)

layer_0 = [[1, 1, 1]]
layer_1 = relu(np.dot(layer_0, weights_l1))
layer_2 = np.dot(layer_1, weights_l2)
print(layer_2)

Error: [[2.67023585]]
[[-1.05525932 -1.15783602  0.33991125  1.85542959]
 [ 1.29224736 -0.80535418  0.1115619  -0.57522552]
 [-0.84288455  1.0939299  -0.719717   -0.20975063]]
[[ 0.75503052]
 [-0.24584093]
 [ 0.49893299]
 [ 0.29902475]]
Error: [[0.00225163]]
[[-1.05525932 -1.15783602  0.33991125  1.6418696 ]
 [ 1.57837532 -0.86607891  0.1115619  -1.19007375]
 [-0.55675659  1.01573659 -0.719717   -0.42331062]]
[[ 0.97914707]
 [-0.00137827]
 [ 0.49893299]
 [ 0.80166149]]
Error: [[5.6968222e-08]]
[[-1.05525932 -1.15783602  0.33991125  1.63793003]
 [ 1.57827223 -0.86607882  0.1115619  -1.21054876]
 [-0.55685968  1.01573562 -0.719717   -0.42725019]]
[[ 9.79039513e-01]
 [-1.42062390e-05]
 [ 4.98932993e-01]
 [ 8.25886465e-01]]
Error: [[1.184773e-12]]
[[-1.05525932 -1.15783602  0.33991125  1.63791337]
 [ 1.57827117 -0.86607882  0.1115619  -1.21064594]
 [-0.55686074  1.01573562 -0.719717   -0.42726684]]
[[ 9.79038405e-01]
 [-1.46429515e-07]
 [ 4.98932993e-01]
 [ 8.26004495e-01]]
Error: [[2.7057